### ISSUE TITLE
[BUG]: Github Actions default working-directory isn't used by the Replexica package

### ISSUE THREAD

**Issue by axelcedercreutz** [lingodotdev/lingo.dev#397]
### What

I'm looking to generate the translations in a Github Action using the `replexica/replexica@main`-package. I want to specify to the action that it should work within a specific directory. I have initialized Replexica in the specific folder and have the  `i18n.json`-file within that folder. Locally, I am able to generate the translations by running `npx replexica@latest i18n` within the specified folder.

The GH Action looks as following:

```
name: Localization

on:
  pull_request:
    branches-ignore:
      - "production**"
      - "dependabot-**"

permissions:
  contents: write
  pull-requests: write

jobs:
  localize:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Replexica Localization
        uses: replexica/replexica@main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          api-key: ${{ secrets.REPLEXICA_API_KEY }}
          pull-request: true
```

However, when running the action, I get the following error:

```
Run replexica/replexica@main
/usr/bin/docker run --name dc3cbd3ae6ea44bb14cb384f32b0cfd3dd0b4_004c06 --label 0dc3cb --workdir /github/workspace --rm -e "GH_TOKEN" -e "INPUT_API-KEY" -e "INPUT_PULL-REQUEST" -e "INPUT_COMMIT-MESSAGE" -e "INPUT_PULL-REQUEST-TITLE" -e "REPLEXICA_API_KEY" -e "REPLEXICA_PULL_REQUEST" -e "REPLEXICA_COMMIT_MESSAGE" -e "REPLEXICA_PULL_REQUEST_TITLE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/{ORGANIZATION}/{REPOSITORY_NAME}":"/github/workspace" 0dc3cb:d3ae6ea44bb14cb384f32b0cfd3dd0b4
ℹ Pull request mode: on
- Configuring git
From {BRANCHNAME}
 * branch              dev-324-investigate-utilization-of-tool-for-translations -> FETCH_HEAD
 * [new branch]        dev-324-investigate-utilization-of-tool-for-translations -> origin/dev-324-investigate-utilization-of-tool-for-translations
Previous HEAD position was f548d17[9](https://github.com/{ORGANIZATION_NAME}/{REPOSITORY_NAME}/actions/runs/12926177618/job/36048643541?pr=296#step:4:10) Merge 9b0ce26c8fff3dff880c19f5898fbcffefcebc0a into 55cdc852d1e0a803083b255a8eab3492d2dc8a13
branch 'dev-324-investigate-utilization-of-tool-for-translations' set up to track 'origin/dev-324-investigate-utilization-of-tool-for-translations'.
Switched to a new branch 'dev-324-investigate-utilization-of-tool-for-translations'
✔ Git configured
- Calculating automated branch name
✔ Automated branch name calculated: replexica/dev-324-investigate-utilization-of-tool-for-translations
- Checking if branch exists
✔ Branch does not exist
- Creating branch replexica/dev-324-investigate-utilization-of-tool-for-translations
From {BRANCH_NAME}
 * branch              dev-324-investigate-utilization-of-tool-for-translations -> FETCH_HEAD
branch 'replexica/dev-324-investigate-utilization-of-tool-for-translations' set up to track 'origin/dev-324-investigate-utilization-of-tool-for-translations'.
Switched to a new branch 'replexica/dev-324-investigate-utilization-of-tool-for-translations'
✔ Created branch replexica/dev-324-investigate-utilization-of-tool-for-translations
- Running Replexica
npm WARN exec The following package was not found and will be installed: replexica@0.66.0
- Loading configuration...
✔ Configuration loaded
- Validating localization configuration...
✖ i18n.json not found. Please run `replexica init` to initialize the project.
 visit: https://docs.replexica.com/quickstart#initialization
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: npx replexica@latest i18n --api-key ***
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at PullRequestFlow.runReplexica (file:///app/build/flows/in-branch.js:39:9)
    at PullRequestFlow.run (file:///app/build/flows/in-branch.js:[12](https://github.com/{ORGANIZATION_NAME}/{REPOSITORY_NAME}/actions/runs/12926177618/job/36048643541?pr=296#step:4:13):20)
    at main (file:///app/build/index.js:17:35) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 36,
  stdout: null,
  stderr: null
}

Node.js v20.12.2
```

### Why
We're using a single repo for multiple apps and we don't want to specify the `i18n.json` to the root.

### How
We should be able to handle in the Action the working directory that is used.

**Comment by maxprilutskiy** [comment]
@axelcedercreutz looking into!

**Comment by mathio** [comment]
Hello @axelcedercreutz 

As [per Github Actions docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/setting-a-default-shell-and-working-directory#setting-default-shell-and-working-directory) this setting is intended to provide default working-directory options for all `run` steps in a workflow. Replexica is not executed in `run` step in your workflow.

I understand your use case, and we are adding support for `working-directory` setting now: https://github.com/lingodotdev/lingo.dev/pull/403

You can use it by passing your working directory to our action like this:
```
      - name: Run Replexica Localization
        uses: replexica/replexica@main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          api-key: ${{ secrets.REPLEXICA_API_KEY }}
          pull-request: true
          working-directory: ./frontend
```

I tested this in my own repo and [it works](https://github.com/mathio/barfoo/actions/runs/12936115859/job/36080980849#step:4:31) 🤞
